name: dddforum
services:
  postgres:
    image: postgres:latest
    ports:
      - "5440:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
